-- Table: chat_messages
-- Description: Stores messages in chat conversations

-- Drop table if exists (useful for development/migrations)
DROP TABLE IF EXISTS chat_messages;

-- Create the chat_messages table
CREATE TABLE chat_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL,
    sender_id UUID NOT NULL,
    message_type VARCHAR(20) NOT NULL DEFAULT 'text',
    content TEXT NOT NULL,
    media_url TEXT,
    media_type VARCHAR(20),
    reply_to_message_id UUID,
    is_edited BOOLEAN DEFAULT FALSE,
    edited_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    
    -- Constraints
    CONSTRAINT fk_chat_messages_sender_id FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_chat_messages_reply_to_message_id FOREIGN KEY (reply_to_message_id) REFERENCES chat_messages(id) ON DELETE SET NULL,
    CONSTRAINT chk_chat_messages_type CHECK (message_type IN ('text', 'image', 'video', 'audio', 'file', 'location', 'system')),
    CONSTRAINT chk_chat_messages_media_type CHECK (media_type IN ('image', 'video', 'audio', 'document', 'other')),
    CONSTRAINT chk_chat_messages_content_or_media CHECK (content IS NOT NULL OR media_url IS NOT NULL)
);

-- Indexes for performance optimization
-- Index on conversation_id for retrieving conversation messages
CREATE INDEX idx_chat_messages_conversation_id ON chat_messages(conversation_id);

-- Index on sender_id for retrieving messages from specific users
CREATE INDEX idx_chat_messages_sender_id ON chat_messages(sender_id);

-- Index on creation date for chronological ordering
CREATE INDEX idx_chat_messages_created_at ON chat_messages(created_at);

-- Index on message type for filtering by media type
CREATE INDEX idx_chat_messages_type ON chat_messages(message_type);

-- Combined index for efficient conversation queries with time ordering
CREATE INDEX idx_chat_messages_conv_created ON chat_messages(conversation_id, created_at);

-- Index on reply_to_message_id for threading messages
CREATE INDEX idx_chat_messages_reply_to ON chat_messages(reply_to_message_id);

-- Index on is_edited for finding edited messages
CREATE INDEX idx_chat_messages_edited ON chat_messages(is_edited);

-- Index for media type queries
CREATE INDEX idx_chat_messages_media_type ON chat_messages(media_type);

-- Function and trigger to set conversation_id based on sender and recipient
-- (Note: In a real implementation, conversation_id would likely come from a conversations table)
-- For this schema, we'll assume conversation_id is provided or generated by the application layer

-- Trigger to update the updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_chat_messages_updated_at 
    BEFORE UPDATE ON chat_messages 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column();

-- Comments for documentation
COMMENT ON TABLE chat_messages IS 'Stores messages in chat conversations';
COMMENT ON COLUMN chat_messages.id IS 'Unique identifier for the message';
COMMENT ON COLUMN chat_messages.conversation_id IS 'ID of the conversation this message belongs to';
COMMENT ON COLUMN chat_messages.sender_id IS 'ID of the user who sent the message';
COMMENT ON COLUMN chat_messages.message_type IS 'Type of the message (text, image, video, etc.)';
COMMENT ON COLUMN chat_messages.content IS 'Text content of the message';
COMMENT ON COLUMN chat_messages.media_url IS 'URL to media content if this is a media message';
COMMENT ON COLUMN chat_messages.media_type IS 'Type of media content';
COMMENT ON COLUMN chat_messages.reply_to_message_id IS 'ID of the message this message is replying to';
COMMENT ON COLUMN chat_messages.is_edited IS 'Indicates if the message has been edited';
COMMENT ON COLUMN chat_messages.edited_at IS 'Timestamp when the message was last edited';
COMMENT ON COLUMN chat_messages.created_at IS 'Timestamp when the message was created';
COMMENT ON COLUMN chat_messages.updated_at IS 'Timestamp when the message was last updated';

-- Add comments to the foreign key constraints
COMMENT ON CONSTRAINT fk_chat_messages_sender_id ON chat_messages IS 'References the users table (sender of the message)';
COMMENT ON CONSTRAINT fk_chat_messages_reply_to_message_id ON chat_messages IS 'References another message in the same conversation (for replies)';