# GitHub Actions workflow for Social Platform CI/CD

name: Social Platform CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        service: [auth-service, user-profile-service, websocket-signaling-service, chat-service, friend-request-service, notification-service, video-call-signaling-service, otp-service]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: apps/services/${{ matrix.service }}/package-lock.json
    
    - name: Install dependencies
      run: |
        cd apps/services/${{ matrix.service }}
        npm ci
    
    - name: Run linting
      run: |
        cd apps/services/${{ matrix.service }}
        npm run lint
    
    - name: Run tests
      run: |
        cd apps/services/${{ matrix.service }}
        npm run test
      env:
        CI: true

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        service: [auth-service, user-profile-service, websocket-signaling-service, chat-service, friend-request-service, notification-service, video-call-signaling-service, otp-service]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
    
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: apps/services/${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          SERVICE_NAME=${{ matrix.service }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Set up Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/kustomize
    
    - name: Update k8s manifests with new image
      run: |
        cd infra/k8s/overlays/staging
        kustomize edit set image ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
    
    - name: Set up kubectl context
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_STAGING }}
    
    - name: Deploy to staging
      run: |
        kubectl kustomize infra/k8s/overlays/staging | kubectl apply -f -
    
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/${{ matrix.service }} -n social-platform-staging

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Set up Kustomize
      run: |
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
        sudo mv kustomize /usr/local/bin/kustomize
    
    - name: Update k8s manifests with new image
      run: |
        cd infra/k8s/overlays/production
        kustomize edit set image ghcr.io/${{ github.repository }}/${{ matrix.service }}:${{ github.sha }}
    
    - name: Set up kubectl context
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG_PRODUCTION }}
    
    - name: Deploy to production
      run: |
        kubectl kustomize infra/k8s/overlays/production | kubectl apply -f -
    
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/${{ matrix.service }} -n social-platform-production

  notify:
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: ${{ always() }}
    
    steps:
    - name: Notify Slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ needs.deploy-staging.result || needs.deploy-production.result }}
        channel: '#deployments'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}
      if: always()